### ISSUE TITLE
Further questions about function use

### ISSUE THREAD

**Issue by daniel-wrench** [fiddir/fBb#2]
Hi again,
I have successfully been able to use your function MFBB on my dataset of interest, which is a time series of the solar wind with gaps missing.
However, I am slightly confused in that the MFBB (in blue, below) seems to be closely following the observed data points (in green) but not exactly matching up with them. Also, does the argument sigma represent the standard deviation of the stochastic process? Thanks.

![image](https://user-images.githubusercontent.com/62724118/218916251-110cb155-ec5f-4f1f-b8dd-3aab1a94b213.png)

**Comment by fiddir** [comment]
Hi Daniel,

Thanks again for using the MFBB function; I'm happy to see it being used on such an applied problem as the gaps in solar wind measurements. 

Unfortunately -  as of now - the MFBB function only works in a very idealized setting, i.e., for equidistantly spaced data and interpolating resolution in multiples of the original data resolution.  What you are seeing in your example is exactly due to this problem as your data is non-equidistant. The construction itself, as detailed in our paper, is an exact interpolator. Hence, this is only an implementation problem in the code, and I'm currently fixing it so that it can cope with more general data types - including your case with gaps in the data. 

Your second question is equally important: Sigma is not exactly the std of the underlying fractional Brownian motion. This might be a bit misleading, but historically, the covariance of the fBm is defined as

<X(t)X(t')>= sigma^2 (t^2H+t'^2H-|t-t'|^2H)/2

Hence, the variance is given as <X(t)^2> = sigma^2 t^2H and is thus non-stationary which makes it hard to match the variance of your signal, and the definition of sigma may depend on what you're further intentions with the bridge process are. A quite useful assumption, which is currently implemented in the code, is that the std of the fBm and your data matches at the largest time scale t.

I hope this clarifies your issues and I will let you know once the non-equidistant version of the MFBB function is implemented (I hope to this by the end of this week).

Best wishes,

Jan

**Comment by daniel-wrench** [comment]
Thanks very much for your detailed and helpful response Jan! I look forward to the update.

**Comment by fiddir** [comment]
Hi Daniel,

No problem; I created a new branch for non-equidistantly spaced data that should suit your problem. Please let me know if you encounter any further issues.

Best,

Jan
